sveedocuments/urls.py
# -*- coding: utf-8 -*-
"""
Root url's map for application
"""
from django.conf.urls import *

from sveedocuments.models import ATTACHMENTS_WITH_SENDFILE
from sveedocuments.views.page import (
    HelpPageView, PageIndexView, PageDetailsView, 
    PageSourceView
)

urlpatterns = patterns('',
    url(r'^$', PageIndexView.as_view(), name='index'),
    
    (r'^board/', include('sveedocuments.urls_board')),
    
    url(r'^help/$', HelpPageView.as_view(), name='help'),
    
    url(r'^(?P<slug>[-\w]+)/$', PageDetailsView.as_view(), name='page-details'),
    url(r'^(?P<slug>[-\w]+)/source/$', PageSourceView.as_view(), name='page-source'),
)

if ATTACHMENTS_WITH_SENDFILE:
    from sveedocuments.views.attachment import AttachmentProtectedDownloadView
    urlpatterns += patterns('',
        url(r'^(?P<slug>[-\w]+)/attachment/(?P<attachment_id>\d+)/$', AttachmentProtectedDownloadView.as_view(), name='page-attachment-download'),
    )

sveedocuments/models.py
# -*- coding: utf-8 -*-
"""
Data models
"""
import warnings
from datetime import datetime

import django.dispatch
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.contrib.auth.models import User
from django.core.cache import cache
from django.utils.translation import ugettext_lazy as _

import mptt
from mptt.models import TreeForeignKey

from rstview.local_settings import RSTVIEW_PARSER_FILTER_SETTINGS

from sveedocuments.utils import _get_cache_keyset
from sveedocuments.utils.filefield import content_file_name

DOCUMENTS_PAGE_TEMPLATES_CHOICES = [(k,v[1]) for k,v in settings.DOCUMENTS_PAGE_TEMPLATES.items()]

DOCUMENTS_VISIBILTY_CHOICES = (
    (True, _('Visible')),
    (False, _('Hidden')),
)

IMAGE_MIMETYPES = (
    'image/gif',
    'image/jpeg',
    'image/png',
    #'image/tiff',
    'image/svg+xml',
)

ATTACH_FILE_UPLOADTO = lambda x,y: content_file_name('pages/attachments/%Y/%m/%d', x, y)

# Check for django-sendfile availibility
try:
    from sendfile import sendfile
except ImportError:
    warnings.warn("Your documents are private but you don't have installed 'django-sendfile' so page attachments will be public for everyone. Install it or set setting 'DOCUMENTS_ATTACHMENT_USE_SENDFILE' to False to avoid this warning.", UserWarning)
    ATTACHMENTS_WITH_SENDFILE = False
    ATTACHMENT_FS_STORAGE = FileSystemStorage(location=settings.MEDIA_ROOT, base_url=settings.MEDIA_URL)
else:
    ATTACHMENTS_WITH_SENDFILE = True
    ATTACHMENT_FS_STORAGE = FileSystemStorage(location=settings.SENDFILE_ROOT, base_url=settings.SENDFILE_URL)


class Insert(models.Model):
    """
    Document to insert
    """
    created = models.DateTimeField(_('created'), blank=True, auto_now_add=True)
    modified = models.DateTimeField(_('last edit'), auto_now=True)
    author = models.ForeignKey(User, verbose_name=_('author'))
    title = models.CharField(_('title'), blank=True, null=True, max_length=255)
    slug = models.SlugField(_('slug'), unique=True, max_length=75)
    visible = models.BooleanField(_('visibility'), choices=DOCUMENTS_VISIBILTY_CHOICES, default=True)
    content = models.TextField(_('content'), blank=False)

    def __unicode__(self):
        return self.slug
    
    def get_render_cache_key(self, **kwargs):
        """
        Get the cache key for the content render according to the given settings
        """
        return settings.INSERT_RENDER_CACHE_KEY_NAME.format(id=self.id, **kwargs)
    
    def get_toc_cache_key(self, **kwargs):
        """
        Get the cache key for the content TOC according to the given settings
        """
        return settings.INSERT_TOC_CACHE_KEY_NAME.format(id=self.id, **kwargs)
    
    def save(self, *args, **kwargs):
        # Invalidate all caches at edit
        if self.modified:
            self.clear_cache()
        
        super(Insert, self).save(*args, **kwargs)
    
    def delete(self, using=None):
        self.clear_cache()
        super(Insert, self).delete(using=using)
    
    def clear_cache(self):
        """
        Invalidate all possible cache keys
        """
        keys = _get_cache_keyset(settings.INSERT_RENDER_CACHE_KEY_NAME, **{
            'id': self.id,
            'setting': RSTVIEW_PARSER_FILTER_SETTINGS.keys(),
            'header_level': ['None']+range(1, 7),
        })
        keys += _get_cache_keyset(settings.INSERT_TOC_CACHE_KEY_NAME, **{
            'id': self.id,
            'setting': RSTVIEW_PARSER_FILTER_SETTINGS.keys(),
            'header_level': ['None']+range(1, 7),
        })
        cache.delete_many(keys)
        return keys
    
    class Meta:
        verbose_name = _("insert document")
        verbose_name_plural = _("insert document")

        
        
class PageModelBase(models.Model):
    """
    Model base for Pages
    """
    created = models.DateTimeField(_('created'), blank=True, editable=False)
    author = models.ForeignKey(User, verbose_name=_('author'))
    title = models.CharField(_('title'), blank=False, max_length=255)
    published = models.DateTimeField(_('publish date'), blank=True, help_text=_("Define when the document will be displayed on the site. Empty value mean an instant publish, use a coming date to program a futur publish."))
    template = models.CharField(_('template'), max_length=50, choices=DOCUMENTS_PAGE_TEMPLATES_CHOICES, default=settings.DOCUMENTS_PAGE_TEMPLATE_DEFAULT, help_text=_("This template will be used to render the page."))
    order = models.SmallIntegerField(_('order'), default=1, help_text=_("Display order in lists and trees."))
    visible = models.BooleanField(_('visibility'), choices=DOCUMENTS_VISIBILTY_CHOICES, default=True)
    content = models.TextField(_('content'), blank=False)
    comment = models.CharField(_('comment'), blank=True, null=True, max_length=255)

    def __unicode__(self):
        return self.title

    def get_template(self):
        return settings.DOCUMENTS_PAGE_TEMPLATES[self.template][0]
    
    class Meta:
        abstract = True    



class Page(PageModelBase):
    """
    Full page document
    """
    modified = models.DateTimeField(_('last edit'), auto_now=True)
    slug = models.SlugField(_('slug'), unique=True, max_length=75, help_text=_("Unique slug used in URL, should be automatically filled with sluggified title."))
    
    @models.permalink
    def get_absolute_url(self):
        return ('documents-page-details', [self.slug])
    
    def get_render_cache_key(self, **kwargs):
        """
        Get the cache key for the content render with according to the given settings
        """
        return settings.PAGE_RENDER_CACHE_KEY_NAME.format(id=self.id, **kwargs)
    
    def get_toc_cache_key(self, **kwargs):
        """
        Get the cache key for the content TOC with according to the given settings
        """
        return settings.PAGE_TOC_CACHE_KEY_NAME.format(id=self.id, **kwargs)
    
    def clear_cache(self):
        """
        Invalidate all possible cache keys
        """
        keys = _get_cache_keyset(settings.PAGE_RENDER_CACHE_KEY_NAME, **{
            'id': self.id,
            'setting': RSTVIEW_PARSER_FILTER_SETTINGS.keys(),
        })
        keys += _get_cache_keyset(settings.PAGE_TOC_CACHE_KEY_NAME, **{
            'id': self.id,
            'setting': RSTVIEW_PARSER_FILTER_SETTINGS.keys(),
        })
        # Drop cache for knowed pages slugs used in the ``page`` rest role
        cache.delete_many([settings.PAGE_SLUGS_CACHE_KEY_NAME]+keys)
        return keys
    
    def _get_current_revision(self):
        return (self.revision.all().aggregate(models.Max('revision')).get('revision__max') or 0)+1
    current_revision = property(_get_current_revision)
    
    def save(self, *args, **kwargs):
        # First create
        if not self.created:
            self.created = datetime.now()
        # Creating a new revision archive
        elif settings.DOCUMENTS_PAGE_ARCHIVED:
            old = Page.objects.get(pk=self.id)
            PageRevision(
                page=self,
                created=self.modified,
                parent=old.parent,
                author=old.author,
                title=old.title,
                published=old.published,
                slug=old.slug,
                template=old.template,
                order=old.order,
                visible=old.visible,
                content=old.content,
                revision=self.current_revision,
                comment=old.comment,
            ).save()
        
        # Fill in the published date with the created date if empty
        if not self.published:
            self.published = self.created
        # Invalidate all caches on edit
        if self.modified:
            self.clear_cache()
        
        super(Page, self).save(*args, **kwargs)
    
    def delete(self, using=None):
        self.clear_cache()
        super(Page, self).delete(using=using)
    
    class Meta:
        verbose_name = _("page")
        verbose_name_plural = _("pages")

# Add a parent foreign key to the model without sublassing MPTTModel
TreeForeignKey(Page, blank=True, null=True, related_name="%(app_label)s_%(class)s_children").contribute_to_class(Page, 'parent')
mptt.register(Page, order_insertion_by=['order', 'title'])



class PageRevision(PageModelBase):
    """
    History revision for a Page document
    """
    slug = models.SlugField(_('slug'), max_length=75)
    page = models.ForeignKey(Page, verbose_name=_('page'), related_name='revision')
    parent = models.ForeignKey(Page, null=True, blank=True, related_name="revision_parent")
    revision = models.IntegerField(_('revision number'), blank=False, default=0, editable=False)
    
    class Meta:
        verbose_name = _("page revision")
        verbose_name_plural = _("pages revisions")


class Attachment(models.Model):
    """
    Attachment file for a Page document
    
    TODO: Remove attachment map cache on update/delete and also when Page is removed, and updated ?
    """
    page = models.ForeignKey(Page, verbose_name=_('page'), related_name='attachment')
    author = models.ForeignKey(User, verbose_name=_('author'))
    title = models.CharField(_('title'), max_length=75, blank=True)
    slug = models.CharField(_('slug'), max_length=75, blank=True, help_text=_("Used as the key to put the attachment in your documents. This does not really use the slug syntax, you can use more special characters. If empty, will be filled with the original file name."))
    created = models.DateTimeField(_('created'), auto_now_add=True)
    file = models.FileField(_('file'), upload_to=ATTACH_FILE_UPLOADTO, storage=ATTACHMENT_FS_STORAGE, max_length=255, blank=False)
    size = models.IntegerField(_('size'), blank=False, default=0, editable=False)
    content_type = models.CharField(_('content_type'), max_length=120, blank=False, null=True, editable=False)
    
    def __unicode__(self):
        return self.slug
    

sveedocuments/forms/insert.py
# -*- coding: utf-8 -*-
"""
Insert forms
"""
from django.conf import settings
from django import forms
from django.utils.translation import ugettext as _

from djangocodemirror.fields import CodeMirrorWidget

from rstview.parser import SourceReporter, map_parsing_errors

from sveedocuments.models import Insert, documents_insert_update_signal
from sveedocuments.forms import CrispyFormMixin
from sveedocuments.forms.page import PageQuickForm

class InsertForm(CrispyFormMixin, forms.ModelForm):
    """
    Insert form
    """
    crispy_form_helper_path = 'sveedocuments.forms.crispies.insert_helper'
    codemirror_config_name = 'sveetchies-documents-add-insert'
    
    def __init__(self, author=None, *args, **kwargs):
        self.author = author
        
        super(InsertForm, self).__init__(*args, **kwargs)
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        
        extra_settings = {}
        if not self.instance.id:
            # Désactive l'option de sauvegarde rapide
            extra_settings = {'quicksave_url': None}
            
        self.fields['content'].widget = CodeMirrorWidget(attrs={'rows': 30}, config_name=self.codemirror_config_name)
    
    def clean_slug(self):
        slug = self.cleaned_data.get("slug")
        if slug:
            if slug in settings.DOCUMENTS_PAGE_RESERVED_SLUGS:
                raise forms.ValidationError(_('This is a reserved keyword'))
        return slug
    
    def clean_content(self):
        """
        Parse le contenu pour vérifier qu'il ne contient par d'erreurs de syntaxe
        """
        content = self.cleaned_data.get("content")
        if content:
            errors = SourceReporter(content)
            if errors:
                raise forms.ValidationError(map(map_parsing_errors, errors))
        return content
    
    def save(self, *args, **kwargs):
        edited = (self.instance and self.instance.id)

        instance = super(InsertForm, self).save(commit=False, *args, **kwargs)
        instance.author = self.author
        instance.save()
        
        # Send a Django signal for page update
        documents_insert_update_signal.send(sender=self, insert_instance=instance, edited=edited)
        
        return instance
    
    class Meta:
        model = Insert
        exclude = ('created', 'author')
        widgets = {
            # Necessary to change "self.fields['content'].widget" in __init__
            'content': CodeMirrorWidget(attrs={'rows': 30}), 
        }


class InsertEditForm(InsertForm):
    crispy_form_helper_path = 'sveedocuments.forms.crispies.insert_edit_helper'
    codemirror_config_name = 'sveetchies-documents-edit-insert'


class InsertQuickForm(PageQuickForm):
    """
    *Insert* quicksave form
    """
    class Meta:
        model = Insert
        fields = ('content',)

sveedocuments/views/board.py
# -*- coding: utf-8 -*-
"""
Board views
"""
from django.views import generic

from djangocodemirror.views import SamplePreviewView, EditorSettingsView

from sveedocuments.models import Page, Insert
from sveedocuments.forms.page import DjangoCodeMirrorSettingsForm

from braces.views import LoginRequiredMixin, PermissionRequiredMixin

class BoardIndexView(LoginRequiredMixin, generic.TemplateView):
    """
    Documents management board
    """
    template_name = "sveedocuments/board/index.html"

    def get(self, request, *args, **kwargs):
        context = {
            'page_count' : Page.objects.count(),
            'page_hidden_count' : Page.objects.filter(visible=False).count(),
            'page_last_revised': Page.objects.all().order_by('-modified')[0:5],
            'insert_count' : Insert.objects.count(),
            'insert_hidden_count' : Insert.objects.filter(visible=False).count(),
        }
        return self.render_to_response(context)

class BoardPagesIndexView(LoginRequiredMixin, generic.TemplateView):
    """
    Board pages index
    """
    template_name = "sveedocuments/board/page_index.html"

    def get(self, request, *args, **kwargs):
        context = {
            'page_list' : Page.objects.filter(),
        }
        return self.render_to_response(context)

class BoardInsertsIndexView(LoginRequiredMixin, generic.TemplateView):
    """
    Board inserts index
    """
    template_name = "sveedocuments/board/insert_index.html"

    def get(self, request, *args, **kwargs):
        context = {
            'insert_list' : Insert.objects.filter().order_by('slug'),
        }
        return self.render_to_response(context)

class PreviewView(LoginRequiredMixin, SamplePreviewView):
    """
    Page preview for a *Page* content
    """
    pass

class BoardEditorSettingsView(LoginRequiredMixin, EditorSettingsView):
    """
    Page form for djangocode-mirror editor settings
    """
    form_class = DjangoCodeMirrorSettingsForm

sveedocuments/templates/sveedocuments/board/base.html
{% extends "skeleton.html" %}
{% load i18n mptt_tags autobreadcrumb documents_admin %}

{% block menu_active_link_documents %} class="active"{% endblock %}

{% block head_title %}{% current_title_from_breadcrumbs %}{% endblock %}
{% block head_base_links %}{{ block.super }}
    {% include "sveedocuments/assets_css.html" %}
{% endblock %}
{% block head_base_js %}{{ block.super }}
    {% include "sveedocuments/assets_js.html" %}
{% endblock %}

{% block base_content %}<div class="row row-fluid documents board">
    <div class="small-12 columns">
        {% autobreadcrumbs_tag %}
    </div>
    
    <div class="small-12 medium-2 columns context-menu">{% spaceless %}

        <ul class="side-nav">
            <li{% block board_menu_summary_active %}{% endblock %}><a href="{% url 'sveedocuments:board' %}">{% trans "Summary" %}</a></li>
            <li{% block board_menu_pages_active %}{% endblock %}><a href="{% url 'sveedocuments:page-index' %}">{% trans "Pages" %}</a></li>
            <li{% block board_menu_inserts_active %}{% endblock %}><a href="{% url 'sveedocuments:insert-index' %}">{% trans "Inserts" %}</a></li>
        </ul>

    {% endspaceless %}</div>
    
    <div class="small-12 medium-10 columns">
        {% block board_content %}{% endblock %}
    </div>
</div>{% endblock %}

sveedocuments/templates/sveedocuments/board/include_css.html
<link rel="stylesheet" href="{{ STATIC_URL }}sveedocuments/css/frontend.css">
<link rel="stylesheet" href="{{ STATIC_URL }}sveedocuments/css/board.css">

sveedocuments/templates/sveedocuments/board/include_js.html
<script src="{{ STATIC_URL }}js/jquery/jquery.slugify.js"></script>
<script src="{{ STATIC_URL }}js/jquery/moment.min.js"></script>
<script src="{{ STATIC_URL }}js/jquery/pikaday.min.js"></script>

sveedocuments/templates/sveedocuments/board/insert_delete.html
{% extends "sveedocuments/board/subbase_inserts.html" %}
{% load i18n documents_menus autobreadcrumb %}

{% block board_content %}
<h2>{% current_title_from_breadcrumbs %}</h2>

<div>
{% pprint_recurse relations %}
</div>

<form action="." method="post">
    {% csrf_token %}
    <div class="buttonHolder panel">
        <input type="submit" name="confirm_delete" value="{% trans "Confirm delete" %}" class="submit button">
    </div>
</form>
{% endblock %}

sveedocuments/templates/sveedocuments/board/insert_form.html
{% extends "sveedocuments/board/subbase_inserts.html" %}
{% load i18n djangocodemirror_inputs djangocodemirror_assets crispy_forms_tags autobreadcrumb %}

{% block head_base_js %}{{ block.super }}
    {% get_current_language as LANGUAGE_CODE %}
    {% include "sveedocuments/board/includes/djangocodemirror_content_assets.html" %}
    <script type="text/javascript">
    //<![CDATA[
    DCM_lang = "{{ LANGUAGE_CODE }}";
    $(document).ready(function() {
        $("#id_slug").slugify("#id_title");
        
        {% if insert_instance %}DJANGOCODEMIRROR_OBJECT = {
            'id': {{ insert_instance.id }},
            'slug': '{{ insert_instance.slug }}'
        };{% endif %}
        
        var content_codemirror_instance = $('#{{ form.content.auto_id }}').djangocodemirror({{ form.content|djangocodemirror_init_input }});
    });
    //]]>
    </script>
{% endblock %}

{% block board_content %}
    <h2>{% current_title_from_breadcrumbs %}</h2>

    {% if messages %}
        {% for message in messages %}
        <div data-alert class="alert-box {% if message.tags %}{{ message.tags }}{% endif %} radius">
        {{ message|safe }}
        <a href="#" class="close">&times;</a>
        </div>
        {% endfor %}
    {% endif %}
    
    {% if insert_instance and insert_instance.visible %}{% include "sveedocuments/board/includes/insert_form_subnav.html" with active_tab="edit" %}{% endif %}

    {% crispy form %}
{% endblock %}

sveedocuments/templates/sveedocuments/board/insert_index.html
{% extends "sveedocuments/board/subbase_inserts.html" %}
{% load i18n mptt_tags autobreadcrumb documents_admin %}

{% block board_content %}
    <div class="clearfix">
        {% if perms.sveedocuments.add_insert %}
            <a class="secondary button right" href="{% url 'sveedocuments:insert-add' %}">{% trans "Add a new insert document" %}</a>
        {% endif %}
        <h2>{% trans "Insert documents" %}</h2>
    </div>
    
    {% if messages %}
        {% for message in messages %}
        <div data-alert class="alert-box {% if message.tags %}{{ message.tags }}{% endif %} radius">
        {{ message|safe }}
        <a href="#" class="close">&times;</a>
        </div>
        {% endfor %}
    {% endif %}
    
    <table class="full">
        <thead>
            <tr>
                <th class="title-cell col-odd">{% trans "Title" %}</th>
                <th class="slug-cell col-even">{% trans "Slug" %}</th>
                <th class="visible-cell col-odd">{% trans "Visibility" %}</th>
                <th class="modified-cell col-even">{% trans "Last modified" %}</th>
                <th class="actions-cell col-odd">#</th>
            </tr>
        </thead>
        <tbody>
    {% for item in insert_list %}
            <tr id="insert-row-{{ item.id }}">
                <th class="title-cell col-odd">
                    {% if perms.sveedocuments.change_insert %}
                        <a href="{% url 'sveedocuments:insert-edit' item.slug %}">{{ item.title }}</a>
                    {% else %}{{ item.title }}{% endif %}
                </th>
                <td class="slug-cell col-even">{{ item.slug }}</td>
                <td class="visible-cell col-odd">{{ item.get_visible_display }}</td>
                <td class="modified-cell col-even">{{ item.modified|date:"l d F Y à H:i"|title }}</td>
                <td class="actions-cell col-odd">
                    {% if perms.sveedocuments.delete_insert %}
                        <a href="{% url 'sveedocuments:insert-delete' item.slug %}">{% trans "Delete" %}</a>
                    {% else %}-{% endif %}
                </td>
            </tr>
        </tr>
    {% endfor %}
        </tbody>
    </table>
{% endblock %}

sveedocuments/templates/sveedocuments/board/page_form.html
{% extends "sveedocuments/board/subbase_pages.html" %}
{% load i18n djangocodemirror_inputs crispy_forms_tags autobreadcrumb %}

{% block head_base_js %}{{ block.super }}
    {% get_current_language as LANGUAGE_CODE %}
    {% include "sveedocuments/board/includes/djangocodemirror_content_assets.html" %}
    <script type="text/javascript">
    //<![CDATA[
    DCM_lang = "{{ LANGUAGE_CODE }}";
    $(document).ready(function() {
        var picker = new Pikaday({
            field: $('#id_published_0')[0],
            //format: 'YYYY-MM-DD',
            format: 'DD/MM/YYYY',
            i18n: {
                months        : ['{% trans "January" %}','{% trans "February" %}','{% trans "March" %}','{% trans "April" %}','{% trans "May" %}','{% trans "June" %}','{% trans "July" %}','{% trans "August" %}','{% trans "September" %}','{% trans "October" %}','{% trans "November" %}','{% trans "December" %}'],
                weekdays      : ['{% trans "Sunday" %}','{% trans "Monday" %}','{% trans "Tuesday" %}','{% trans "Wednesday" %}','{% trans "Thursday" %}','{% trans "Friday" %}','{% trans "Saturday" %}'],
                weekdaysShort : ['{% trans "Sun" %}','{% trans "Mon" %}','{% trans "Tue" %}','{% trans "Wed" %}','{% trans "Thu" %}','{% trans "Fri" %}','{% trans "Sat" %}']
            }
        });
        
        $("#id_slug").slugify("#id_title");
        
        {% if page_instance %}DJANGOCODEMIRROR_OBJECT = {
            'id': {{ page_instance.id }},
            'slug': '{{ page_instance.slug }}'
        };{% endif %}
        
        var content_codemirror_instance = $('#{{ form.content.auto_id }}').djangocodemirror({{ form.content|djangocodemirror_init_input }});
    });
    //]]>
    </script>
{% endblock %}

{% block board_content %}
    <h2>{% current_title_from_breadcrumbs %}</h2>

    {% if messages %}
        {% for message in messages %}
        <div data-alert class="alert-box {% if message.tags %}{{ message.tags }}{% endif %} radius">
        {{ message|safe }}
        <a href="#" class="close">&times;</a>
        </div>
        {% endfor %}
    {% endif %}
    
    {% if page_instance and page_instance.visible %}{% include "sveedocuments/board/includes/page_form_subnav.html" with active_tab="edit" %}{% endif %}
    
    {% crispy form %}
{% endblock %}

sveedocuments/templates/sveedocuments/board/page_index.html
{% extends "sveedocuments/board/subbase_pages.html" %}
{% load i18n mptt_tags autobreadcrumb documents_admin %}

{% block foot_more_js %}
    <script type="text/javascript">
    //<![CDATA[
    $(document).ready(function() {
        $('.list-jqtree').jqtree_documents_index({
            'state_cookie_name': 'sveedocuments_admin_tree_all',
            'link_add_child_title': '{% trans "New child page" %}',
            'link_delete_title': '{% trans "Delete" %}',
            'admin_mode': true,
            'json_tree_data': {{ json_tree|safe }}
        });
    });
    //]]>
    </script>
{% endblock %}

{% block board_content %}
        <div class="clearfix">
            <ul class="button-group radius right">
                <li><a class="button tiny secondary tree-open-link" href="#"><i class="icon-plus-square"></i> {% trans "Open all" %}</a></li>
                <li><a class="button tiny secondary tree-close-link" href="#"><i class="icon-minus-square"></i> {% trans "Close all" %}</a></li>
                {% if perms.sveedocuments.add_page %}
                    <li><a class="button tiny" href="{% url 'sveedocuments:page-add' %}">{% trans "Add a new page" %}</a></li>
                {% endif %}
            </ul>
            <h2>{% trans "Pages" %}</h2>
        </div>
        
        {% if messages %}{% for message in messages %}
            <div data-alert class="alert-box {% if message.tags %}{{ message.tags }}{% endif %} radius">
            {{ message|safe }}
            <a href="#" class="close">&times;</a>
            </div>
        {% endfor %}{% endif %}

        <div class="list-jqtree"></div>

        <noscript>{% spaceless %}
            <ul class="list-tree-fluid">{% recursetree page_list %}
                <li class="tree-item{% if not node.visible %} hidden{% endif %}">
                
                    <div class="indicator">
                        <span class="has-tip" data-width="90" title="{{ node.get_visible_display }}"><i class="lsf">{% if node.visible %}<i class="icon-eye"></i>{% else %}<i class="icon-eye-slash"></i>{% endif %}</i></span>
                        <span class="has-tip" data-width="210" title="{% blocktrans with published=node.published|date:"d/m/Y H:i" %}Published on {{ published }}{% endblocktrans %}"><i class="icon-calendar"></i></span>
                    </div>
                    
                    <div class="clearfix">
                        {% if perms.sveedocuments.change_page %}
                            <a href="{% url 'sveedocuments:page-edit' node.slug %}" class="button split">{{ node.title }} <span data-dropdown="page-drop-{{ node.id }}"></span></a><br>
                        {% else %}
                            <a href="#" data-dropdown="page-drop-{{ node.id }}" class="button{% if perms.sveedocuments.add_page or perms.sveedocuments.delete_page %} dropdown{% endif %}">{{ node.title }}</a><br>
                        {% endif %}
                        
                        {% if perms.sveedocuments.add_page or perms.sveedocuments.delete_page %}
                        <ul id="page-drop-{{ node.id }}" class="f-dropdown" data-dropdown-content>
                            {% if perms.sveedocuments.add_page %}
                                <li><a href="{% url 'sveedocuments:page-add-child' node.slug %}" title="{% blocktrans %}Add a new child page to this one{% endblocktrans %}">{% trans "New child page" %}</a></li>
                            {% endif %}
                            {% if perms.sveedocuments.delete_page %}
                            <li><a href="{% url 'sveedocuments:page-delete' node.slug %}" title="{% blocktrans %}Recursively delete this page and his children{% endblocktrans %}">{% trans "Delete" %}</a></li>
                            {% endif %}
                        </ul>
                        {% endif %}
                    </div>
                    
                    {% if not node.is_leaf_node %}<ul class="children {% if not node.visible %}hidden_parent{% endif %}">{{ children }}</ul>{% endif %}
                </li>
            {% endrecursetree %}</ul>
        {% endspaceless %}</noscript>
{% endblock %}

sveedocuments/templates/sveedocuments/board/subbase_inserts.html
{% extends "sveedocuments/board/base.html" %}

{% block board_menu_inserts_active %} class="active"{% endblock %}